#user  nginx;
worker_processes  1;

error_log /dev/stdout info;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log  /dev/stdout;

    sendfile        on;

    keepalive_timeout  65;

    brotli on;
    brotli_static on;
    brotli_types text/plain text/css application/javascript application/json image/svg+xml application/xml+rss;


    include /etc/nginx/conf.d/*.conf;

    server {
        listen 8080;
        listen [::]:8080;

        server_name localhost;
        root /app/dist;
        index index.html index.htm;

        location /readiness {
          return 200 'ok';
        }

        location /liveness {
          return 200 'ok';
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
