ingress:
  enabled: true
  objects:
    - servicePort: 80
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      hosts:
        - name: {{ .Helm.Release.Namespace }}-ingress-controller.{{ .Helm.Release.Namespace }}.{{ .Helm.Release.Cluster }}
          path: /pvz-plan(/|$)(.*)

env:
  APP_BASE_URL: /pvz-plan/